[tool.mypy]
overrides = [
  { module = "geopandas", ignore_missing_imports = true },
  { module = "docker", ignore_missing_imports = true },
  { module = "docker.errors", ignore_missing_imports = true }
]
