# .github/workflows/python-ci.yml
name: Python CI

on: [push, pull_request]

jobs:
  mypy:
    name: Mypy Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          pip install -r requirements.txt  # Ensure your requirements.txt includes needed dependencies

      - name: Run mypy
        run: |
          ./scripts/check_types.sh

  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # or any other testing library you use

      - name: Run tests
        run: |
          ./scripts/check_tests.sh

